# languages
# (name, local to planet of origin)
("Basic", 0)
("Binary", 0)
("Bocce", 0)
("Bothese", 0)
("Cerean", 0)
("Dosh", 0)
("Durese", 0)
("Ewokese", 1)
("Gamorrean", 0)
("Gunganese", 1)
("High Galactic", 0)
("Huttese", 0)
("Ithorese", 0)
("Jawa Trade Language", 1)
("Kel Dor", 0)
("Mon Calamarian", 0)
("Quarranese", 0)
("Rodese", 0)
("Ryl", 0)
("Shyriiwook", 0)
("Sullustese", 0)
("Zabrak", 0)
